// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efModels
{
    public partial class ArtPiece
    {
        public ArtPiece()
        {
            ArtType = new HashSet<ArtType>();
            Contributor = new HashSet<Contributor>();
            License = new HashSet<License>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string TmbUri { get; set; }
        public string MainUri { get; set; }

        public virtual ICollection<ArtType> ArtType { get; set; }
        public virtual ICollection<Contributor> Contributor { get; set; }
        public virtual ICollection<License> License { get; set; }
    }
}