// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efModels
{
    public partial class Contributor
    {
        public Contributor()
        {
            ArtPiece = new HashSet<ArtPiece>();
        }

        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string FriendlyId { get; set; }

        public virtual ICollection<ArtPiece> ArtPiece { get; set; }
    }
}