// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace efModels
{
    public partial class sp_coloringPagesIndexResult
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string tmbURI { get; set; }
        public string mainURI { get; set; }
        public string Contributors { get; set; }
        public string Licenses { get; set; }
        public string ArtTypes { get; set; }
    }
}
