// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace efModels
{
    public partial class sp_getBlogEntryResult
    {
        public string title { get; set; }
        public string URI { get; set; }
    }
}
