// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace efModels
{
    public partial class sp_getBlogListResult
    {
        public string friendlyId { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public int day { get; set; }
        public string subId { get; set; }
        public string title { get; set; }
    }
}
